apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "example-app.fullname" . }}
spec:
  rules:
  - host: example-app.example.com 
    http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "example-app.fullname" . }}
                port:
                  number: 80
