apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    app: {{ include "example-app.fullname" . }}
spec:
  selector:
    app.kubernetes.io/instance: {{ include "example-app.fullname" . }}
    app.kubernetes.io/name: {{ include "example-app.fullname" . }}   
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
